[package]
name = "dicenotation"
version = "0.1.0"
authors = ["Mattias Cibien <mattias@mattiascibien.net>"]

[dependencies]
lazy_static = "1.0"
regex = "0.2"
rand = "0.4"

[dev-dependencies]
clap = "2.31"